const TileType = {
	PATH: 0,
	FOREST_BACK_LEFT: 1,
	FOREST_BACK_MID: 2,
	FOREST_BACK_RIGHT: 3,
	FOREST_LEFT: 4,
	FOREST: 5,
	FOREST_RIGHT: 6,
	FOREST_FRONT_LEFT: 7,
	FOREST_FRONT_MID: 8,
	FOREST_FRONT_RIGHT: 9,
};